defaults:
  - _self_
  - workspace_config
  - agent: fb_ddpg

hydra:
  run:
    dir: /mnt/data_7tb/fanfeng/cnnfb/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
  sweep:
    dir: /mnt/data_7tb/fanfeng/cnnfb/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}_${experiment}
    subdir: ${hydra.job.num}




# dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${agent.feature_learner}_${task}_${experiment}
#     submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${agent.feature_learner}_${task}_${experiment}/.slurm
